<?php

/**
 * @file
 * Puts the comment form into a block and provides a default view for the
 * comments.
 * We can now easily sort stuff and add fields.
 */

/*
 * implementation of hook_menu()
 */

function commentsblock_menu() {
  $items['admin/config/user-interface/commentsblock'] = array(
    'title' => 'Comments Block',
    'description' => 'How to display the comments block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commentsblock_settings_form'),
    'access arguments' => array('administer comment blocks'),
    'file' => 'commentsblock.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implementation of hook_views_api().
 * The view is automatically inlcuded via commentsblock_views_default_views() if path is correct see doku:
 * http://drupalcontrib.org/api/drupal/contributions--views--docs--views.api.php/function/hook_views_default_views/7
 */
function commentsblock_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commentsblock') . '/views',
  );
}


/**
 * Implementation of hook_nodeapi().
 *
 * This will make room for your custom comment view, by removing the regular
 * comment listing from the node body.
 *
 * @todo the unset is not a good solution? maybe difficulties with other modules?
 */

function commentsblock_node_view($node, $view_mode, $langcode) {
  //unset the comments because we render them
  unset($node->content['comments']);
  //setting the anker right, seems hacky, find a better way
  $node->content['links']['comment']['#links']['comment-add']['fragment'] = 'comment-form--2';
}


/**
 * Implements hook_block_info().
 */

function commentsblock_block_info() {
  $blocks = array();
  $blocks['comment_form_block'] = array(
    'info' => t('Comment form block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * We use a custom view for the comment display and put the block in a form
 * OR
 * We put form+comments in the form
 */

function commentsblock_block_view($delta) {
  $block = '';
  $display_option = variable_get('commentsblock_display', '');

  switch ($delta) {
    case 'comment_form_block':

      // Only nodes in page view.
      if ((arg(0) == 'node') && is_numeric(arg(1)) && (arg(2) == NULL)) {

        $node = menu_get_object('node');

        // Only display the form if we are allowed to post comments.
        if (user_access('post comments') && $node->comment > 1) {
          $block['subject'] = t('Post new comment');

          if ($display_option == 0) {
            //load only the form
            $block['content'] = drupal_get_form("comment_node_{$node->type}_form", (object)array('nid' => $node->nid));
          }
          else {
            //load form+all comments
            $block['content'] = comment_node_page_additions($node);
          }
        }

      }
      break;
  }
  return $block;
}

